import random
from collections import deque

WORKING = [
    "flow state unlocked",
    "weaving logic",
    "thoughts into code",
    "vibing w/ interp",
    "architecting reality",
    "fluent in machine",
    "in the zone",
    "threading the needle",
    "sculpting functions",
    "rendering ideas",
    "mainframe hacking",
    "linter dance",
    "rewriting reality",
    "locked in",
    "forging features",
    "cooking in the IDE",
    "galaxy-brained",
    "shipping thoughts",
    "mind-melding repo",
    "abstraction stack",
    "copilot whisperer",
    "next unicorn arc",
    "typing at 200 wpm",
    "deep in the sauce",
    "pattern matching",
    "do not disturb",
    "caffeinated af",
    "big brain engaged",
    "DDD pilled",
    "in my coding era",
    "prod money printer",
    "linter coping",
    "keyboard posture L",
    "refactoring reality",
    "building the future",
    "touching the monad",
    "feature grindset",
    "vibes on 100",
    "cooking up something",
    "shipping vibes",
    "one w/ the repo",
    "IDE whisperer",
    "git add . energy",
    "keyboard on fire",
    "absolutely cracked",
    "locked in vault",
    "aura up",
    "hacker type beat",
    "brain vs blank file",
    "on the grindset",
    "vibe coding era",
    "claude-pilled",
    "agentic workflow",
    "LLM copilot arc",
    "sigma dev grind",
    "prompt-engineered",
    "ratio the compiler",
    "W dev moment",
    "cooked clean code",
]

DEBUGGING = [
    "debugging reality",
    "ghost hunting",
    "stack trace ritual",
    "bisecting the void",
    "compiler beef",
    "abyss staring",
    "console.log pilled",
    "bending spoons",
    "chasing heisenbugs",
    "reading tea leaves",
    "decoding errors",
    "runtime whisperer",
    "breakpoint digs",
    "untangling spaghetti",
    "praying to the stack",
    "works on my pc",
    "bug elsewhere",
    "2am rubber duck",
    "gdb enjoyer",
    "9h in, 1 line left",
    "retracing my steps",
    "git reset --hard",
    "step debugging",
    "npm audit cope",
    "call inside the file",
    "print debug era",
    "bug has no mercy",
    "blaming the cache",
    "blaming the network",
    "blaming the intern",
    "SO wont save me",
    "ctrl-z speedrun",
    "bug hunt arc",
    "segfault era",
    "catching em all",
    "null is not valid",
    "off-by-one again",
    "reading err aloud",
    "comment til green",
    "git bisect gang",
    "career regret arc",
    "the tests lied",
    "3am breakthrough",
    "duck consultation",
    "1 char, 4h hunt",
    "tsc trust issues",
    "race condition arc",
    "the real bug is us",
    "it's always DNS",
    "merge conflict hell",
    "L debugging moment",
    "skill issue detected",
    "ratio'd by runtime",
    "bricked by caching",
    "delulu stack trace",
]

TESTING = [
    "stress testing",
    "writing tests (lol)",
    "green means go",
    "red, green, refactor",
    "mocking everything",
    "asserting dominance",
    "coverage maxxing",
    "making CI cry",
    "snapshot diffing",
    "fuzzing reality",
    "expect(life).pass",
    "property-based",
    "edge case hunting",
    "flaky test enjoyer",
    "TDD enjoyer",
    "unit test artisan",
    "integration tests",
    "100% coverage arc",
    "proving it works",
    "assertion matrix",
    "jest enjoyer",
    "pytest pilled",
    "mocha brewing",
    "playwright pilled",
    "regression speedrun",
    "golden file guardian",
    "fixture matrix",
    "table-driven zen",
    "snapshot vibes",
    "ci pipeline nerd",
    "meta-tests pilled",
    "arrange, act, assert",
    "green board no notes",
    "e2e endurance run",
    "pinning prod",
    "red bar, big sigh",
    "test doubles forever",
    "vitest enjoyer",
    "cypress summoner",
    "hermetic tests",
    "contract testing",
    "mutation testing",
    "edge cases pending",
    "qa hat on",
    "bug catching vibes",
    "coverage-maxxing",
    "CI is cooking",
    "flake arc",
    "testing pilled",
    "green board W",
]

BUILDING = [
    "shipping to cosmos",
    "bundling ambition",
    "compiling dreams",
    "webpack thinking",
    "rollup time",
    "building artifacts",
    "docker whispering",
    "vite speedrun",
    "tree-shaking",
    "transpiling vibes",
    "linking phase",
    "esbuild go brrr",
    "minifying destiny",
    "build gods cooking",
    "cargo --release",
    "maven ate internet",
    "gradle gradling",
    "tsc please be fast",
    "next build incoming",
    "turbopack go brr",
    "bun install arc",
    "pnpm lockfile arc",
    "waiting on CI",
    "container baking",
    "pushing to registry",
    "hot reload gang",
    "source map juggling",
    "dep graph gardening",
    "wasm curious",
    "ship it anyway",
    "make -j infinity",
    "watching the spinner",
    "paint compiling",
    "Dockerfile audit",
    "progress bar stare",
    "let it cook",
    "cache hits go brrr",
    "nx affected speedrun",
    "bazel sandbox tour",
    "deploy preview",
    "bundle going lean",
    "ship prep vibes",
    "all green build",
    "CDN warming up",
    "CI cooking",
    "build is cooking",
    "shipped different",
    "build W",
]

COMMITTING = [
    "pushing momentum",
    "commit to the bit",
    "immortalizing work",
    "git got this",
    "blaming future me",
    "atomic commit",
    "sealing the deal",
    "etching history",
    "signing the ledger",
    "branch enjoyer",
    "merge conflict W",
    "conv commits pilled",
    "squashing the past",
    "rebasing reality",
    "force push prayer",
    "the tree grows",
    "another green square",
    "keeping the streak",
    "cherry-picking",
    "one commit closer",
    "bugs are trembling",
    "cosmic shipping",
    "git history go up",
    "commit count +1",
    "sealed & signed",
    "progress locked in",
    "HEAD moves forward",
    "velocity +1",
    "timestamp of triumph",
    "small win banked",
    "new hash who dis",
    "the tree remembers",
    "checksum gang",
    "main gets fed",
    "deltas packed",
    "touching git",
    "SHA-1 says nice",
    "push or perish",
    "fast-forward vibes",
    "rebased and based",
    "stash empty, soul W",
    "staged & ascended",
    "CI, please be kind",
    "hooks passed W",
    "diff approved",
    "pre-commit passed",
    "working tree clean",
    "zero warnings energy",
    "shipped with love",
    "portfolio-worthy",
    "tiny commit big W",
    "cooked and shipped",
    "commit goated",
    "git W",
    "based commit",
]

STATE_POOLS = {
    "working": WORKING,
    "debugging": DEBUGGING,
    "testing": TESTING,
    "building": BUILDING,
    "committing": COMMITTING,
}

_recent = {}
_RECENT = 10


def next_vibe(state):
    pool = STATE_POOLS.get(state, WORKING)
    seen = _recent.setdefault(state, deque(maxlen=_RECENT))
    choices = [v for v in pool if v not in seen] or pool
    pick = random.choice(choices)
    seen.append(pick)
    return pick
